In [15]:
# -*- coding: utf-8 -*-
"""
Created on Wed Apr 22 05:42:28 2020

@author: paras
"""

import pandas as pd
import numpy as np
from sklearn.externals import joblib 

from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer

df = pd.read_csv("Churn_Modelling.csv")

df_x = df.iloc[:, 3:13]
df_y = df.iloc[:, 13]

df_x.head()

# df.isna().sum()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,France,Female,42,2,0.00,1,1,1,101348.88
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58
2,502,France,Female,42,8,159660.80,3,1,0,113931.57
3,699,France,Female,39,1,0.00,2,0,0,93826.63
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10

In [16]:
def clean_data(df):

    le = LabelEncoder()
    df.Gender = le.fit_transform(df.Gender)
    df = pd.get_dummies(data = df, columns=["Geography"], drop_first = False)
    df = df.sort_index(axis=1)
    return df

In [17]:
df_x = clean_data(df_x)
# df_x.head()

In [18]:
# df_one = pd.DataFrame(df_x.iloc[2, :])
# df_one = df_one.T
# df_one
# clean_data(df_one)

In [19]:
# columnTransformer = ColumnTransformer([('encoder', OneHotEncoder(), [1])], remainder='passthrough')
# col_tnf = columnTransformer.fit_transform(df_x)
# df_x = np.array(col_tnf, dtype = np.str)
# df_x = df_x[:, 1:]

In [20]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df_x, df_y, test_size = 0.2, random_state = 0)
print(X_train)
joblib.dump(X_train.columns, "columns.pkl")

      Age    Balance  CreditScore  EstimatedSalary  Gender  Geography_France  \
7389   34       0.00          667        163830.64       0                 0
9275   42   75681.52          427         57098.00       1                 0
2995   29  112367.34          535        185630.76       0                 1
5316   40  105683.63          654        173617.09       1                 0
356    57  126776.30          850        132298.49       0                 0
49     37  103769.22          776        194099.12       0                 0
7931   47   95120.59          807        127875.10       1                 1
1523   41       0.00          598        161954.43       1                 0
7552   76  126534.60          636         39789.62       1                 0
496    32  169089.38          622        101057.95       0                 1
5110   33   74963.50          682         32770.56       0                 1
1957   54  171137.62          710        167023.95       1                 1
229    29  130830.22          594         61048.53       0                 0
1738   41  107525.07          796         18510.41       1                 0
7789   38   99897.53          606         37054.65       1                 0
7567   44       0.00          629        117572.59       1                 1
4787   42  157498.90          529         82276.62       1                 1
2607   31  118870.92          814        101704.19       1                 1
3784   31  138857.59          640         48640.77       0                 1
8879   43       0.00          809        132908.07       1                 1
1003   42  175159.90          646         67124.48       0                 1
5676   26       0.00          749         34948.77       0                 1
4853   41  135203.81          684        121967.88       0                 1
8946   28       0.00          623        129526.57       1                 1
9038   50   98173.02          803         22457.25       0                 0
3042   29  130420.20          835        106276.55       0                 0
8277   40  149961.99          624        104610.86       0                 0
5979   24  148298.59          677        182913.95       0                 1
2075   45  108231.37          710        188574.08       1                 0
4482   42       0.00          653          5768.32       0                 1
...   ...        ...          ...              ...     ...               ...
755    31  157120.86          803        141300.53       1                 1
8291   38  147904.31          668         69370.05       1                 0
2496   45       0.00          567        121053.19       0                 1
7599   45  158621.04          537        120892.96       0                 1
1871   36   85996.19          634         15887.68       1                 0
2046   34  120018.86          520           343.38       1                 0
7877   41   69974.66          494        188426.13       0                 0
4851   48       0.00          530         85081.09       0                 1
5072   29  102490.27          472        181224.56       1                 1
2163   35       0.00          605         45206.57       1                 1
6036   27   79144.34          674         50743.83       0                 1
6921   39   91187.90          679          6075.36       0                 0
6216   47       0.00          479         95270.83       1                 1
537    34       0.00          686        127569.80       1                 0
9893   40  100480.53          764        124095.69       0                 1
2897   29  170214.23          528         49284.00       0                 0
7768   20  122446.61          601         86791.90       0                 0
2222   43   39043.29          711        175423.69       1                 0
2599   62   80927.56          550         64490.67       1                 0
705    40  168286.81          750         20451.99       1                 0
3468   49       0.00          820        119087.25       0                 1
6744   30       0.00          777        115611.97       0                 1
5874   19       0.00          597         91036.74       1                 1
4373   45       0.00          546        197789.83       0                 0
7891   48  101099.90          678        193476.04       1                 0
9225   32  120074.97          594        162961.79       0                 0
4859   22  114440.24          794        107753.07       0                 0
3264   35  161274.05          738        181429.87       1                 1
9845   38       0.00          590        148750.16       0                 0
2732   48  108076.33          623        118855.26       0                 0

      Geography_Germany  Geography_Spain  HasCrCard  IsActiveMember  \
7389                  0                1          1               0
9275                  1                0          1               1
2995                  0                0          1               0
5316                  0                1          1               0
356                   0                1          1               1
49                    1                0          1               0
7931                  0                0          0               0
1523                  0                1          1               1
7552                  0                1          1               1
496                   0                0          1               0
5110                  0                0          1               1
1957                  0                0          1               1
229                   1                0          1               0
1738                  0                1          1               0
7789                  1                0          0               0
7567                  0                0          0               0
4787                  0                0          1               1
2607                  0                0          1               0
3784                  0                0          1               0
8879                  0                0          1               1
1003                  0                0          0               0
5676                  0                0          0               1
4853                  0                0          1               1
8946                  0                0          0               0
9038                  1                0          0               0
3042                  1                0          0               0
8277                  1                0          1               0
5979                  0                0          0               0
2075                  1                0          1               1
4482                  0                0          1               1
...                 ...              ...        ...             ...
755                   0                0          1               0
8291                  0                1          1               1
2496                  0                0          0               1
7599                  0                0          1               0
1871                  0                1          1               0
2046                  1                0          1               1
7877                  0                1          1               0
4851                  0                0          1               0
5072                  0                0          0               1
2163                  0                0          1               1
6036                  0                0          0               1
6921                  0                1          0               1
6216                  0                0          1               0
537                   0                1          1               0
9893                  0                0          1               0
2897                  1                0          1               0
7768                  0                1          1               0
2222                  1                0          1               1
2599                  0                1          0               1
705                   1                0          1               0
3468                  0                0          1               1
6744                  0                0          0               1
5874                  0                0          1               1
4373                  0                1          0               0
7891                  1                0          0               1
9225                  1                0          1               1
4859                  0                1          1               1
3264                  0                0          1               0
9845                  0                1          1               1
2732                  1                0          1               0

      NumOfProducts  Tenure
7389              2       5
9275              1       1
2995              1       2
5316              1       5
356               2       8
49                2       2
7931              1       1
1523              2       8
7552              1       9
496               2       6
5110              1       8
1957              1       6
229               1       3
1738              1       8
7789              1       3
7567              4       5
4787              1       1
2607              1       1
3784              1       9
8879              2       2
1003              2       3
5676              2       6
4853              2       6
8946              1       7
9038              1       8
3042              2      10
8277              2       3
5979              2       0
2075              1       9
4482              2       1
...             ...     ...
755               2       9
8291              1       1
2496              2       4
7599              1       7
1871              1       2
2046              2       8
7877              2       2
4851              1       0
5072              1       8
2163              2       6
6036              1       4
6921              1       7
6216              1       1
537               2       9
9893              1       9
2897              2       9
7768              2       9
2222              2       2
2599              1       7
705               3       5
3468              2       1
6744              2       4
5874              2       2
4373              1       2
7891              2       2
9225              2       4
4859              1       4
3264              2       5
9845              2       9
2732              1       1

[8000 rows x 12 columns]

['columns.pkl']

In [21]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
joblib.dump(scaler, "std_scaler.pkl")
print(X_test)
print(X_train.shape[1])

[[-0.36890377  0.8793029  -0.55204276 ...  0.9687384  -0.92159124
   1.04473698]
 [ 0.10961719  0.42972196 -1.31490297 ... -1.03227043 -0.92159124
  -1.031415  ]
 [ 0.30102557  0.30858264  0.57162971 ...  0.9687384  -0.92159124
   1.04473698]
 ...
 [-0.27319958  1.29745526 -0.74791227 ... -1.03227043  0.8095029
  -1.37744033]
 [-0.46460796  1.05975239 -0.00566991 ...  0.9687384  -0.92159124
  -0.33936434]
 [-0.84742473  0.82026342 -0.79945688 ... -1.03227043 -0.92159124
   1.04473698]]
12

C:\Users\paras\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:645: DataConversionWarning: Data with input dtype uint8, int32, int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\paras\Anaconda3\lib\site-packages\sklearn\base.py:464: DataConversionWarning: Data with input dtype uint8, int32, int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)
C:\Users\paras\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: Data with input dtype uint8, int32, int64, float64 were all converted to float64 by StandardScaler.
  after removing the cwd from sys.path.

In [22]:
import keras
from keras.models import Sequential
from keras.layers import Dense

classifier = Sequential()
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = X_train.shape[1]))
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
classifier.fit(X_train, y_train, batch_size = 10, epochs = 20)

Epoch 1/20
8000/8000 [==============================] - 1s 91us/step - loss: 0.5077 - accuracy: 0.7956
Epoch 2/20
8000/8000 [==============================] - 1s 81us/step - loss: 0.4316 - accuracy: 0.7960
Epoch 3/20
8000/8000 [==============================] - 1s 85us/step - loss: 0.4286 - accuracy: 0.7960
Epoch 4/20
8000/8000 [==============================] - 1s 87us/step - loss: 0.4263 - accuracy: 0.7960
Epoch 5/20
8000/8000 [==============================] - 1s 88us/step - loss: 0.4238 - accuracy: 0.7960
Epoch 6/20
8000/8000 [==============================] - 1s 88us/step - loss: 0.4207 - accuracy: 0.8150
Epoch 7/20
8000/8000 [==============================] - 1s 89us/step - loss: 0.4180 - accuracy: 0.8231
Epoch 8/20
8000/8000 [==============================] - 1s 86us/step - loss: 0.4155 - accuracy: 0.8255
Epoch 9/20
8000/8000 [==============================] - 1s 95us/step - loss: 0.4139 - accuracy: 0.8300
Epoch 10/20
8000/8000 [==============================] - 1s 92us/step - loss: 0.4123 - accuracy: 0.8314
Epoch 11/20
8000/8000 [==============================] - 1s 87us/step - loss: 0.4114 - accuracy: 0.8339 0s - loss: 0.4065 - accura
Epoch 12/20
8000/8000 [==============================] - 1s 93us/step - loss: 0.4102 - accuracy: 0.8331
Epoch 13/20
8000/8000 [==============================] - 1s 87us/step - loss: 0.4093 - accuracy: 0.8346
Epoch 14/20
8000/8000 [==============================] - 1s 88us/step - loss: 0.4086 - accuracy: 0.8330
Epoch 15/20
8000/8000 [==============================] - 1s 85us/step - loss: 0.4082 - accuracy: 0.8342
Epoch 16/20
8000/8000 [==============================] - 1s 88us/step - loss: 0.4074 - accuracy: 0.8349
Epoch 17/20
8000/8000 [==============================] - 1s 87us/step - loss: 0.4072 - accuracy: 0.8330
Epoch 18/20
8000/8000 [==============================] - 1s 101us/step - loss: 0.4068 - accuracy: 0.8351
Epoch 19/20
8000/8000 [==============================] - 1s 106us/step - loss: 0.4066 - accuracy: 0.8355
Epoch 20/20
8000/8000 [==============================] - 1s 107us/step - loss: 0.4060 - accuracy: 0.8361

In [23]:
y_pred = classifier.predict(X_test)
print(y_pred)
y_pred = (y_pred > 0.5)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
accuracy = (cm[0,0]+cm[1, 1])/(cm[0,0]+cm[1, 1]+cm[1,0]+cm[0, 1])
print(accuracy)
joblib.dump(classifier, 'prediction_classifier.pkl')

[[0.26999915]
 [0.34106222]
 [0.19596693]
 ...
 [0.17759994]
 [0.11842605]
 [0.12583756]]
0.8375

['prediction_classifier.pkl']